# Generated by Django 4.2.6 on 2023-11-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('Usernamename', models.CharField(max_length=100)),
            ],
        ),
    ]
